name = "user3"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
routes = [
  { pattern = "user3.hehdinn.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.user3.hehdinn.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.user3.hehdinn.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.user3.hehdinn.web.id", custom_domain = true },
  { pattern = "investors.spotify.com.user3.hehdinn.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.user3.hehdinn.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.user3.hehdinn.web.id", custom_domain = true },
  { pattern = "blog.webex.com.user3.hehdinn.web.id", custom_domain = true },
  { pattern = "support.zoom.us.user3.hehdinn.web.id", custom_domain = true },
]
[vars]
PROXYIP = "103.6.207.108:8080"
UUID = "15d69360-a893-4698-8f91-ead9e95b7330"
SOCKS5 = "127.0.0.1:1080"
SOCKS5_RELAY = "true"
